Repository codeit5-Team8/torip-frontend, pull requests merged in 2024-12, with the labels that each got.

#38 [#25] Popup 컴포넌트 구현
  src/app/layout.tsx
  src/app/store/popup.store.ts
  src/app/ui/common/Popup.tsx
Labels: ✨feat✨

#41 [#40] breakpoint 수정
  src/app/ui/common/Popup.tsx
  tailwind.config.ts
Labels: 🍜리뷰 3초컷🍜, 🛠️refactor🛠️

#44 [#32] Button 컴포넌트 사이즈 width 값 수정
  src/app/ui/common/Button.tsx
Labels: 🍜리뷰 3초컷🍜, 🛠️refactor🛠️

#43 [#36] Todo CheckBox 컴포넌트
  public/asset/image/check-icon.svg
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/asset/image/.sample
  src/app/ui/common/CheckBox.tsx
Labels: ✨feat✨

#46 [#26] Input 공통 컴포넌트 제작
  components.json
  components/ui/select.tsx
  package-lock.json
  package.json
  src/app/globals.css
  src/app/types/input.ts
  src/app/ui/common/Input.tsx
  src/app/ui/common/PasswordInput.tsx
  src/app/ui/common/SelectInput.tsx
  src/constant/input.ts
  src/lib/utils.ts
  tailwind.config.ts
Labels: ✨feat✨

#53 [#52] MainLayout 컴포넌트 컨테이너 영역 레이아웃 수정
  src/ui/common/SideBar.tsx
  src/ui/layout/MainLayout.tsx
  tailwind.config.ts
Labels: 🛠️refactor🛠️

#55 [#54] Popup 컴포넌트 사용법 개편 - usePopup hook 생성
  src/hooks/.sample
  src/hooks/usePopup.ts
  src/store/popup.store.ts
  src/ui/common/Popup.tsx
  tailwind.config.ts
Labels: 🛠️refactor🛠️

#58 [#57] usePopup hook import문 수정
  src/hooks/usePopup.ts
Labels: 🍜리뷰 3초컷🍜, 📌fix📌

#60 56/auth
  public/asset/image/kakao.png
  public/logo-icon.png
  public/logo.png
  src/app/(authorized)/playground/page.tsx
  src/app/(unauthorized)/layout.tsx
  src/app/(unauthorized)/signin/page.tsx
  src/app/(unauthorized)/signup/page.tsx
  src/constant/auth.ts
  src/constant/input.ts
  src/types/input.ts
  src/ui/auth/AuthInput.tsx
  src/ui/common/Button.tsx
  src/ui/common/Input.tsx
  src/ui/common/Logo.tsx
  src/ui/common/PasswordInput.tsx
  src/ui/layout/AuthLayout.tsx
  tailwind.config.ts
Labels: 📌fix📌, ✨feat✨

#64 [#49] Modal 컴포넌트 구현
  src/app/layout.tsx
  src/hooks/useModal.ts
  src/store/modal.store.ts
  src/ui/common/Modal.tsx
  src/ui/common/Popup.tsx
Labels: ✨feat✨

#70 [#62] TaskCard 컴포넌트
  components/ui/progress.tsx
  components/ui/select.tsx
  package-lock.json
  package.json
  src/constant/Task.ts
  src/constant/index.ts
  src/ui/card/taskCard/TaskCard.tsx
  src/ui/card/taskCard/TaskItem.tsx
  src/ui/card/taskCard/TaskList.tsx
  src/ui/card/taskCard/TaskProgressBar.tsx
Labels: ✨feat✨

#72 [#42] Sidebar 컴포넌트 구현
  public/asset/icon/expand.png
  public/asset/icon/flag.png
  public/asset/icon/fold.png
  public/asset/icon/home.png
  public/asset/icon/plus-mint.png
  public/asset/icon/plus.png
  public/asset/image/profile.png
  src/hooks/usePopup.ts
  src/hooks/useResize.ts
  src/ui/common/SideBar.tsx
  src/ui/common/SidebarContent.tsx
  src/ui/common/TodoModal.tsx
  src/ui/common/TripModal.tsx
  src/ui/layout/MainLayout.tsx
  tailwind.config.ts
Labels: ✨feat✨

#80 [#69] Modal, Popup UI 버그 수정 & hook 제거
  src/hooks/useModal.ts
  src/hooks/usePopup.ts
  src/store/modal.store.ts
  src/store/popup.store.ts
  src/ui/common/Modal.tsx
  src/ui/common/Popup.tsx
  src/ui/common/SidebarContent.tsx
Labels: 📌fix📌, 🛠️refactor🛠️

#84 [#78] 여행 별 노트 모아보기 페이지 구현
  src/app/(authorized)/(note)/note-all-trip/[tripId]/layout.tsx
  src/app/(authorized)/(note)/note-all-trip/[tripId]/page.tsx
  src/constant/note.ts
  src/constant/path.ts
  src/model/note.model.ts
  src/test/note/NoteHeader.test.tsx
  src/ui/common/NavTitle.tsx
  src/ui/note/Divider.tsx
  src/ui/note/NoteAddButton.tsx
  src/ui/note/NoteAllTripInfo.tsx
  src/ui/note/NoteDraft.tsx
  src/ui/note/NoteHeader.tsx
  src/ui/note/NoteInfo.tsx
  src/ui/note/NoteItem.tsx
  src/ui/note/NoteList.tsx
  src/ui/note/NoteListEmpty.tsx
  src/ui/note/NoteTaskInfo.tsx
  src/util/common.ts
Labels: ✨feat✨

#82 [#76] DropdownMenu trigger 버튼 아이콘이나 텍스트, 스타일 정의 추가
  src/ui/common/ButtonIconGroup.tsx
  src/ui/common/DropdownMenu.tsx
Labels: 🍜리뷰 3초컷🍜, 🛠️refactor🛠️

#90 [#76] DropdownMenu 병합하면서 태그 닫힘 누락 수정
  src/ui/common/ButtonIconGroup.tsx
Labels: 🍜리뷰 3초컷🍜, 📌fix📌

#93 [#83] SideBar 컴포넌트 구조 수정
  src/ui/SideBar/Dashboard.tsx
  src/ui/SideBar/SideBar.tsx
  src/ui/SideBar/SideBarContent.tsx
  src/ui/SideBar/SideBarHeader.tsx
  src/ui/SideBar/TripList.tsx
  src/ui/SideBar/UserInfo.tsx
  src/ui/common/SideBar.tsx
  src/ui/common/SidebarContent.tsx
  src/ui/layout/MainLayout.tsx
Labels: 🍜리뷰 3초컷🍜, 🛠️refactor🛠️, 🏃‍♀️신속🏃

#98 [#92] 여행 상세 페이지 UI (여행 정보, 노트 모아보기)
  src/app/(authorized)/(trip)/trip/[id]/page.tsx
  src/ui/trip/TripInfo.tsx
  src/ui/trip/TripNotesButton.tsx
Labels: ✨feat✨

#103 [#86] 노트 상세 페이지 구현
  package-lock.json
  package.json
  src/app/(authorized)/(note)/(list)/@drawer/(.)note-detail/[noteId]/page.tsx
  src/app/(authorized)/(note)/(list)/@drawer/default.tsx
  src/app/(authorized)/(note)/(list)/layout.tsx
  src/app/(authorized)/(note)/(list)/note-all-trip/[tripId]/layout.tsx
  src/app/(authorized)/(note)/(list)/note-all-trip/[tripId]/page.tsx
  src/app/(authorized)/(note)/(list)/note-detail/[noteId]/page.tsx
  src/app/api/proxy/route.ts
  src/app/globals.css
  src/app/layout.tsx
  src/model/note.model.ts
  src/ui/common/Drawer.tsx
  src/ui/common/NavTitle.tsx
  src/ui/note/NoteBackDrop.tsx
  src/ui/note/NoteDetail.tsx
  src/ui/note/NoteDetailDrawerWrapper.tsx
  src/ui/note/NoteDrawer.tsx
  src/ui/note/NoteIframe.tsx
  src/ui/note/NoteInfo.tsx
  src/ui/note/NoteItem.tsx
  src/ui/note/NoteTitle.tsx
  src/ui/note/NoteTripTitle.tsx
  src/ui/note/NoteViewer.tsx
  src/util/note.ts
Labels: ✨feat✨

#106 [#100] 빌드 에러 디버깅
  src/hooks/useResize.ts
  src/ui/note/NoteItem.tsx
Labels: 📌fix📌

#115 [#114] 여행 상세 할 일 API 연동
  src/app/(authorized)/(trip)/trip/[id]/layout.tsx
  src/app/(authorized)/(trip)/trip/[id]/page.tsx
  src/constant/Task.ts
  src/constant/queryKeyFactory.ts
  src/hooks/task/useDeleteTask.ts
  src/lib/api/service/task.api.ts
  src/model/task.model.ts
  src/provider/QueryProvider.tsx
  src/ui/card/taskCard/TaskCard.tsx
  src/ui/card/taskCard/TaskItem.tsx
  src/ui/card/taskCard/TaskList.tsx
  src/ui/card/taskCard/TaskProgressBar.tsx
  src/ui/carousel/TaskCarousel.tsx
  src/ui/common/ButtonIconGroup.tsx
  src/ui/common/FilterButton.tsx
  src/ui/trip/TripTask.tsx
Labels: ✨feat✨

#116 [#97] 여행 정보 API 연동
  src/app/(authorized)/(trip)/trip/[id]/page.tsx
  src/constant/queryKeyFactory.ts
  src/constant/trip.ts
  src/hooks/trip/useDeleteTrip.ts
  src/hooks/trip/useGetTrip.ts
  src/lib/api/service/trip.api.ts
  src/model/trip.model.ts
  src/ui/common/Skeleton.tsx
  src/ui/trip/TripInfo.tsx
  src/ui/trip/TripNotesButton.tsx
  src/util/ calculateDDay.ts
  src/util/.sample
Labels: ✨feat✨

#120 [#119] 할 일&여행 생성 및 수정 hooks 구현
  src/hooks/task/usePostTask.ts
  src/hooks/task/usePutTask.ts
  src/hooks/trip/usePatchTrip.ts
  src/hooks/trip/usePostTrip.ts
  src/model/task.model.ts
  src/ui/SideBar/UserInfo.tsx
  src/ui/common/Modal.tsx
Labels: ✨feat✨

#121 [#117] 여행 멤버 API 연동
  src/constant/queryKeyFactory.ts
  src/constant/trip.ts
  src/hooks/trip/useGetJoinTripList.ts
  src/hooks/trip/useGetTripMembers.ts
  src/hooks/trip/usePostAcceptTrip.ts
  src/hooks/trip/usePostJoinTrip.ts
  src/hooks/trip/usePostRejectTrip.ts
  src/ui/common/Modal.tsx
  src/ui/trip/TripInfo.tsx
  src/ui/trip/tripMember/TripMemberModal.tsx
  src/ui/trip/tripMember/TripMemberSection.tsx
  src/ui/trip/tripMember/tripJoinRequest/TripJoinRequest.tsx
  src/ui/trip/tripMember/tripParticipant/TripParticipant.tsx
Labels: ✨feat✨

#125 [#97] 여행 수정 모달 연결 및 수정/삭제 메뉴 관리자 외 접근 제한 처리
  src/hooks/trip/usePatchTrip.ts
  src/ui/trip/TripInfo.tsx
Labels: ✨feat✨

#126 [#94] SideBar - 여행 생성 & 수정 모달 구현
  package-lock.json
  package.json
  src/app/layout.tsx
  src/ui/Modal/DateRangePicker.tsx
  src/ui/Modal/Modal.tsx
  src/ui/Modal/TodoModal.tsx
  src/ui/Modal/TripModal.tsx
  src/ui/Modal/TripTitle.tsx
  src/ui/SideBar/SideBar.tsx
  src/ui/SideBar/SideBarContent.tsx
  src/ui/box/TripBox.tsx
  src/ui/common/Header.tsx
  src/ui/common/TripModal.tsx
  src/ui/layout/MainLayout.tsx
  src/ui/trip/TripTask.tsx
Labels: 🛠️refactor🛠️, ✨feat✨

#128 [#114] 할일 수정 모달 연결
  src/hooks/task/usePutTask.ts
  src/model/task.model.ts
  src/ui/card/taskCard/TaskItem.tsx
Labels: ✨feat✨

#132 [#114] 여행/할 일 수정 모달 폴더 이동과 누락 import 수정
  src/ui/card/taskCard/TaskItem.tsx
  src/ui/trip/TripInfo.tsx
Labels: 🍜리뷰 3초컷🍜, 📌fix📌, 🏃‍♀️신속🏃
