Repository codeit5-Team8/torip-frontend, pull requests merged in 2024-11, with the labels that each got.

#2 [#1] SearchBar 컴포넌트 제작
  README.md
Labels: ✨feat✨, SearchBar

#11 [#3] Speed Insights 설치
  next.config.mjs
  next.config.ts
  package-lock.json
  package.json
  src/app/layout.tsx
Labels: Setting

#14 [#3] 빌드 에러 해결
  src/app/layout.tsx
Labels: Setting

#15 dev -> main
  src/app/layout.tsx
Labels: Setting

#12 [#10] GitHub Actions 세팅
  .github/workflows/main.yml
  package.json
Labels: Setting

#18 [#3] Sentry 설치
  .gitignore
  next.config.mjs
  package-lock.json
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/api/sentry-example-api/route.ts
  src/app/global-error.tsx
  src/app/layout.tsx
  src/app/sentry-example-page/page.tsx
  src/instrumentation.ts
Labels: Setting

#17 [#16] GitHub Actions 실행 시 comment 등록 조건 수정
  .github/workflows/main.yml
Labels: 📌fix📌

#19 dev -> main
  .github/workflows/main.yml
  .gitignore
  next.config.mjs
  package-lock.json
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/api/sentry-example-api/route.ts
  src/app/global-error.tsx
  src/app/layout.tsx
  src/app/sentry-example-page/page.tsx
  src/instrumentation.ts
Labels: Setting

#23 [#22] Tailwind CSS 글로벌 스타일 설정
  src/app/globals.css
  tailwind.config.ts
Labels: ⚙️Setting⚙️

#24 [#21] Axios 기본 셋팅
  src/app/lib/api/axios.ts
Labels: ⚙️Setting⚙️
