Repository codeit5-Team8/torip-frontend, pull requests merged in 2025-01, with the labels that each got.

#136 [#118] 여행 공유(초대)하기
  next.config.mjs
  src/app/(authorized)/(trip)/trip/[id]/page.tsx
  src/app/(authorized)/(trip)/trip/layout.tsx
  src/app/(unauthorized)/signin/page.tsx
  src/app/(unauthorized)/signup/page.tsx
  src/app/layout.tsx
  src/constant/trip.ts
  src/hooks/trip/usePostAcceptTrip.ts
  src/hooks/trip/usePostJoinTrip.ts
  src/hooks/trip/usePostRejectTrip.ts
  src/lib/api/service/trip.api.ts
  src/middleware.ts
  src/model/trip.model.ts
  src/ui/card/taskCard/TaskItem.tsx
  src/ui/common/EmptyMessage.tsx
  src/ui/trip/TripInfo.tsx
  src/ui/trip/TripJoinAccess.tsx
  src/ui/trip/tripMember/tripJoinRequest/TripJoinRequest.tsx
  src/ui/trip/tripMember/tripJoinRequest/TripJoinRequestItem.tsx
  src/ui/trip/tripMember/tripParticipant/TripParticipantItem.tsx
Labels: 🛠️refactor🛠️, ✨feat✨

#138 [#130] 할 일 생성 및 수정 모달 구현
  src/hooks/file/useUploadFile.ts
  src/hooks/task/usePostTask.ts
  src/hooks/trip/usePatchTrip.ts
  src/hooks/trip/usePostTrip.ts
  src/lib/api/service/file.api.ts
  src/lib/api/service/task.api.ts
  src/model/file.model.ts
  src/model/task.model.ts
  src/ui/Modal/DDayPicker.tsx
  src/ui/Modal/FileUploader.tsx
  src/ui/Modal/MultiselectInput.tsx
  src/ui/Modal/TodoModal.tsx
  src/ui/Modal/TodoScope.tsx
  src/ui/Modal/TodoTitle.tsx
  src/ui/Modal/TripModal.tsx
  src/ui/Modal/TripPicker.tsx
  src/ui/Modal/TripStep.tsx
  src/ui/Modal/TripTitle.tsx
  src/ui/SideBar/SideBar.tsx
  src/ui/SideBar/SideBarContent.tsx
  src/ui/SideBar/TripList.tsx
  src/ui/SideBar/UserInfo.tsx
  src/ui/common/SelectInput.tsx
Labels: ✨feat✨

#165 [#163] Modal 컴포넌트 수정사항 반영
  public/asset/icon/delete.png
  src/ui/Modal/Modal.tsx
  src/ui/Modal/TodoModal.tsx
  src/ui/Modal/TripPicker.tsx
Labels: 📌fix📌, 🛠️refactor🛠️

#172 [#171] Modal 컴포넌트 타입 에러 수정
  src/model/task.model.ts
Labels: 📌fix📌, 🏃‍♀️신속🏃

#173 [#152] 로그인 오류 해결 - redirectTo 타입 수정
  src/app/(unauthorized)/signin/page.tsx
Labels: 🍜리뷰 3초컷🍜, 📌fix📌, 🏃‍♀️신속🏃

#175 SideBar 컴포넌트 로고 수정
  public/asset/image/logo_full.png
  public/logo-icon.png
  public/logo.png
  src/ui/common/Logo.tsx
Labels: 📌fix📌

#176 메인 로고 PNG 파일 생성, SideBar on/off 제어
  public/asset/logo.png
  public/asset/logo_icon.png
  src/ui/SideBar/SideBarHeader.tsx
  src/ui/common/Logo.tsx
Labels: 📌fix📌, 🛠️refactor🛠️

#177 Modal 닫을 시 출력되는 confirm 창 제거
  src/ui/Modal/Modal.tsx
  src/ui/Modal/TodoModal.tsx
Labels: 🛠️refactor🛠️

#183 리팩토링 및 버그 fix
  src/ui/SideBar/TripList.tsx
Labels: 📌fix📌

#181 Fix/dashboarderror
  src/model/task.model.ts
  src/model/user.model.ts
  src/ui/box/AllTodoBox.tsx
  src/ui/card/taskCard/TaskItem.tsx
  src/ui/card/taskCard/TaskList.tsx
  src/ui/common/ButtonIconGroup.tsx
  src/ui/trip/TripTask.tsx
Labels: 📌fix📌, 🛠️refactor🛠️

#184 [#182] 로그인/회원가입, 대시보드, 여행 상세 Error 해결
  components/ui/progress.tsx
  src/app/(authorized)/todo-all/page.tsx
  src/app/(unauthorized)/signin/page.tsx
  src/app/(unauthorized)/signup/page.tsx
  src/hooks/task/usePutCompleteTask.ts
  src/ui/box/TripBox.tsx
  src/ui/common/DropdownMenu.tsx
  src/ui/common/FilterButton.tsx
  src/ui/skeleton/Skeletons.tsx
  src/ui/trip/TripTask.tsx
Labels: 📌fix📌, 🛠️refactor🛠️

#186 [#129] Kakao Login
  src/app/(unauthorized)/signin/page.tsx
  src/lib/api/service/auth.api.ts
  src/lib/authOptions.ts
  src/lib/next-auth.d.ts
  src/model/auth.model.ts
  src/model/model.ts
Labels: 🛠️refactor🛠️, ✨feat✨
